In [25]:
import pandas as pd
import numpy as np

In [26]:
# checking encoding type
meta = pd.read_csv('data.processed/meta_extract.csv', encoding='utf-8') 
meta.head(20)

,url,title,runtime,rating,metascore,userscore,genre,cast,director,studio,awards
0,https://www.metacritic.com/movie/!women-art-re...,!Women Art Revolution,83.0,| Not Rated,70,NaN,Documentary,NaN,Lynn Hershman-Leeson,Hotwire Productions,NaN
1,https://www.metacritic.com/movie/10-cloverfiel...,10 Cloverfield Lane,104.0,| PG-13,76,7.7,"Action,Sci-Fi,Drama,Mystery,Thriller,Horror","John Gallagher Jr.,John Goodman,Mary Elizabeth...",Dan Trachtenberg,Paramount Pictures,"#18MostDiscussedMovieof2016 , #1MostSharedMovi..."
2,https://www.metacritic.com/movie/10-items-or-less,10 Items or Less,82.0,| R,54,5.8,"Drama,Comedy,Romance","Jonah Hill,Morgan Freeman,Paz Vega",Brad Silberling,Click Star,NaN
3,https://www.metacritic.com/movie/10-years,10 Years,100.0,| R,61,6.9,"Drama,Comedy,Romance","Channing Tatum,Chris Pratt,Jenna Dewan",Jamie Linden,Anchor Bay Entertainment,NaN
4,https://www.metacritic.com/movie/100-bloody-acres,100 Bloody Acres,91.0,| Not Rated,63,7.5,"Horror,Comedy",NaN,Cameron Cairnes,Music Box Films,NaN
5,https://www.metacritic.com/movie/100-streets,100 Streets,93.0,NaN,44,6.1,Drama,NaN,Jim O'Hanlon,Samuel Goldwyn Films,NaN
6,https://www.metacritic.com/movie/1000-times-go...,"1,000 Times Good Night",117.0,| Not Rated,57,6.8,Drama,NaN,Erik Poppe,Film Movement,NaN
7,https://www.metacritic.com/movie/10000-bc,"10,000 BC",109.0,| PG-13,34,4.6,"Adventure,Drama,Fantasy","Camilla Belle,Marco Khan,Steven Strait",Roland Emmerich,Warner Bros. Pictures,"#23MostDiscussedMovieof2008 , #27MostSharedMov..."
8,https://www.metacritic.com/movie/10000-km,"10,000 km",99.0,| R,75,7.4,"Drama,Comedy,Romance",NaN,Carlos Marques-Marcet,Broad Green Pictures,NaN
9,https://www.metacritic.com/movie/1001-grams,1001 Grams,93.0,| Not Rated,65,NaN,Drama,NaN,Bent Hamer,Kino Lorber,NaN
10,https://www.metacritic.com/movie/101-reykjavik,ReykjavÃ­k,88.0,| Not Rated,68,5.4,"Comedy,Romance","Hilmir SnÃ¦r GuÃ°nason,Victoria Abril",Baltasar KormÃ¡kur,Menemsha Entertainment,NaN
11,https://www.metacritic.com/movie/102-dalmatians,102 Dalmatians,100.0,| G,35,5.1,"Comedy,Family","GÃ©rard Depardieu,Glenn Close",Kevin Lima,Buena Vista Pictures,#73MostDiscussedMovieof2000
12,https://www.metacritic.com/movie/10th-wolf,10th & Wolf,107.0,| R,36,6.7,"Drama,Mystery,Thriller,Crime","Brad Renfro,Giovanni Ribisi,James Marsden",Robert Moresco,THINKFilm,NaN
13,https://www.metacritic.com/movie/11-flowers,11 Flowers,110.0,| Not Rated,71,NaN,Drama,NaN,Xiaoshuai Wang,First Run Features,NaN
14,https://www.metacritic.com/movie/11-minutes,11 Minutes,81.0,| Not Rated,51,7.5,"Drama,Thriller",NaN,Jerzy Skolimowski,IFC Films,NaN
15,https://www.metacritic.com/movie/11816,11/8/16,104.0,| TV-MA,62,NaN,Documentary,Abby Linne,Alison Klayman,The Orchard,NaN
16,https://www.metacritic.com/movie/12,12,159.0,| PG-13,72,7.4,"Drama,Thriller,Crime,War","Apti Magamaev,Sergei Makovetsky,Sergey Garmash",Nikita Mikhalkov,Sony Pictures Classics,"#97BestMovieof2009 , #18MostSharedMovieof2009"
17,https://www.metacritic.com/movie/12-12-12,12-12-12,105.0,| R,54,NaN,Documentary,NaN,Amir Bar-Lev,"Weinstein Company, The",NaN
18,https://www.metacritic.com/movie/12-hour-shift,12 Hour Shift,87.0,| Not Rated,63,5.8,"Thriller,Horror,Comedy","Angela Bettis,Brooke Seguin,Chloe Farnworth,Da...",Brea Grant,Magnet Releasing,NaN
19,https://www.metacritic.com/movie/12-mighty-orp...,12 Mighty Orphans,118.0,| PG-13,44,6.6,"History,Sport","Carlson Young,Jacob Lofland,Jake Austin Walker...",Ty Roberts,Sony Pictures Classics,NaN

In [27]:
# detect the real encoding
import chardet

with open('data.processed/meta_extract.csv', 'rb') as f:
    result = chardet.detect(f.read(100000))
print(result)

{'encoding': 'utf-8', 'confidence': 0.99, 'language': ''}

In [28]:
# test encoding on one string
test = "GÃ©rard Depardieu"
fixed = test.encode('latin1').decode('utf-8')
print(fixed)

Gérard Depardieu

In [29]:
# apply encoding to the real column
meta['cast'] = meta['cast'].str.encode('latin1', errors='ignore').str.decode('utf-8', errors='ignore')
meta['cast'].head(20)

0                                                   NaN
1     John Gallagher Jr.,John Goodman,Mary Elizabeth...
2                    Jonah Hill,Morgan Freeman,Paz Vega
3                Channing Tatum,Chris Pratt,Jenna Dewan
4                                                   NaN
5                                                   NaN
6                                                   NaN
7                Camilla Belle,Marco Khan,Steven Strait
8                                                   NaN
9                                                   NaN
10                  Hilmir Snær Guðnason,Victoria Abril
11                         Gérard Depardieu,Glenn Close
12            Brad Renfro,Giovanni Ribisi,James Marsden
13                                                  NaN
14                                                  NaN
15                                           Abby Linne
16       Apti Magamaev,Sergei Makovetsky,Sergey Garmash
17                                                  NaN
18    Angela Bettis,Brooke Seguin,Chloe Farnworth,Da...
19    Carlson Young,Jacob Lofland,Jake Austin Walker...
Name: cast, dtype: str

In [30]:
# split the cast column into individual actors
cast_long = meta['cast'].dropna().str.split(',').explode().str.strip()

In [31]:
# build the unique cast_member table
cast_member = (
    cast_long
    .drop_duplicates()
    .to_frame(name='cast_name')
    .reset_index(drop=True)
)
cast_member.insert(0, 'cast_id', cast_member.index + 1)
cast_member.head(20)

    cast_id                cast_name
0         1       John Gallagher Jr.
1         2             John Goodman
2         3  Mary Elizabeth Winstead
3         4               Jonah Hill
4         5           Morgan Freeman
5         6                 Paz Vega
6         7           Channing Tatum
7         8              Chris Pratt
8         9              Jenna Dewan
9        10            Camilla Belle
10       11               Marco Khan
11       12            Steven Strait
12       13     Hilmir Snær Guðnason
13       14           Victoria Abril
14       15         Gérard Depardieu
15       16              Glenn Close
16       17              Brad Renfro
17       18          Giovanni Ribisi
18       19            James Marsden
19       20               Abby Linne

In [32]:
cast_member.info

<bound method DataFrame.info of        cast_id                cast_name
0            1       John Gallagher Jr.
1            2             John Goodman
2            3  Mary Elizabeth Winstead
3            4               Jonah Hill
4            5           Morgan Freeman
...        ...                      ...
24857    24858           Ninon François
24858    24859        Patrick Boucheron
24859    24860          Sayyid El Alami
24860    24861         Wislanda Louimat
24861    24862            Victoria Hall

[24862 rows x 2 columns]>

In [ ]:
# export the result
cast_member.to_csv('data.processed/cast_member_extract.csv', index=False, encoding='utf-8')

In [35]:
# verify by reopening the exported file
check = pd.read_csv('data.processed/cast_member_extract.csv')
check[check['cast_name'].str.contains('nnaeson|rard', na=False)]

       cast_id            cast_name
14          15     Gérard Depardieu
344        345        Gerard Butler
3267      3268         Ana Girardot
3704      3705         Gerard Horan
4806      4807    Nolan Gerard Funk
4997      4998  Simone-Élise Girard
5956      5957       Luis Gerardo M
6549      6550         Gerard Catus
7500      7501   Eliza Brady-Girard
7684      7685    Ella-June Henrard
11751    11752       Caitlin Gerard
11843    11844   Hippolyte Girardot
15864    15865        Gérard Jugnot
17105    17106       Annie Girardot
19245    19246     Gérard Dessalles
19356    19357          Rémy Girard

In [36]:
cast_member.tail(20)

       cast_id              cast_name
24842    24843          Dennis Mallen
24843    24844            Megan Hayes
24844    24845            Nasir Rahim
24845    24846       Nelcie Souffrant
24846    24847      Pedro Tavarez Jr.
24847    24848            Steve Heinz
24848    24849             Tony Demil
24849    24850             Ts Madison
24850    24851            Adilé David
24851    24852          Ginite Popote
24852    24853        Katiana Milfort
24853    24854         Louise Labeque
24854    24855        Mackenson Bijou
24855    24856           Mathilde Riu
24856    24857  Néhémy Pierre-Dahomey
24857    24858         Ninon François
24858    24859      Patrick Boucheron
24859    24860        Sayyid El Alami
24860    24861       Wislanda Louimat
24861    24862          Victoria Hall

In [37]:
cast_member.shape

(24862, 2)